begin;

insert into public.sources (
  id,
  name,
  url,
  type,
  category,
  active,
  priority,
  parser_key,
  last_success_at,
  last_error_at,
  consecutive_failures,
  offers_found,
  notes,
  created_at,
  updated_at
)
values
  (
    'source-design-systems-jobs',
    'Design Systems Jobs',
    'https://designsystems.jobs/',
    'manual',
    'design-systems',
    true,
    10,
    'design-systems-manual',
    timezone('utc', now()) - interval '1 day',
    null,
    0,
    34,
    'Fuente nicho de alta señal para roles de componentes y sistemas.',
    timezone('utc', now()) - interval '90 days',
    timezone('utc', now()) - interval '1 day'
  ),
  (
    'source-design-engineer',
    'Design Engineer',
    'https://designengineer.io/',
    'manual',
    'design-engineering',
    true,
    10,
    'design-engineer-manual',
    timezone('utc', now()) - interval '2 days',
    null,
    0,
    18,
    'Alta afinidad para perfiles híbridos diseño + CSS + frontend.',
    timezone('utc', now()) - interval '90 days',
    timezone('utc', now()) - interval '2 days'
  ),
  (
    'source-uiux-jobs-board',
    'UI/UX Jobs Board',
    'https://uiuxjobsboard.com/',
    'scrape',
    'generalist',
    true,
    7,
    'uiuxjobsboard-html',
    timezone('utc', now()) - interval '3 days',
    null,
    0,
    52,
    'Volumen medio, señal mixta.',
    timezone('utc', now()) - interval '60 days',
    timezone('utc', now()) - interval '3 days'
  ),
  (
    'source-authentic-jobs',
    'Authentic Jobs',
    'https://authenticjobs.com/',
    'api',
    'generalist',
    true,
    7,
    'authentic-jobs-api',
    timezone('utc', now()) - interval '2 days',
    null,
    0,
    61,
    'Generalista con bastante volumen y bastantes roles de diseño.',
    timezone('utc', now()) - interval '120 days',
    timezone('utc', now()) - interval '2 days'
  ),
  (
    'source-weworkremotely',
    'We Work Remotely',
    'https://weworkremotely.com/',
    'scrape',
    'remote',
    true,
    6,
    'weworkremotely-html',
    timezone('utc', now()) - interval '4 days',
    null,
    0,
    71,
    'Muy útil para remoto; filtrar fuerte por rol.',
    timezone('utc', now()) - interval '150 days',
    timezone('utc', now()) - interval '4 days'
  ),
  (
    'source-ai-design-jobs',
    'AI Design Jobs',
    'https://ai-design-jobs.vercel.app/',
    'manual',
    'niche-design',
    true,
    8,
    'ai-design-jobs-manual',
    timezone('utc', now()) - interval '5 days',
    null,
    0,
    12,
    'Nicho emergente; revisar calidad antes de elevar prioridad.',
    timezone('utc', now()) - interval '45 days',
    timezone('utc', now()) - interval '5 days'
  ),
  (
    'source-astrolabium',
    'Astrolabium',
    'https://astrolabium.substack.com/',
    'manual',
    'newsletter',
    true,
    5,
    'astrolabium-rss',
    timezone('utc', now()) - interval '2 days',
    null,
    0,
    9,
    'Curación manual; útil para calidad, no para volumen.',
    timezone('utc', now()) - interval '75 days',
    timezone('utc', now()) - interval '2 days'
  ),
  (
    'source-getmanfred',
    'Manfred',
    'https://www.getmanfred.com/',
    'api',
    'ats-direct',
    true,
    8,
    'manfred-api',
    timezone('utc', now()) - interval '3 days',
    null,
    0,
    27,
    'Buena señal en mercado técnico-producto en España.',
    timezone('utc', now()) - interval '130 days',
    timezone('utc', now()) - interval '3 days'
  ),
  (
    'source-greenhouse-boards',
    'Greenhouse Boards',
    'https://boards.greenhouse.io/',
    'ats',
    'ats-direct',
    true,
    9,
    'greenhouse-json',
    timezone('utc', now()) - interval '1 day',
    null,
    0,
    88,
    'ATS directo; alta fiabilidad estructural.',
    timezone('utc', now()) - interval '180 days',
    timezone('utc', now()) - interval '1 day'
  ),
  (
    'source-lever-direct',
    'Lever Direct',
    'https://jobs.lever.co/',
    'ats',
    'ats-direct',
    false,
    8,
    'lever-json',
    timezone('utc', now()) - interval '6 days',
    timezone('utc', now()) - interval '2 days',
    2,
    20,
    'Desactivada temporalmente por errores recientes de parsing.',
    timezone('utc', now()) - interval '100 days',
    timezone('utc', now()) - interval '2 days'
  )
on conflict (id) do update set
  name = excluded.name,
  url = excluded.url,
  type = excluded.type,
  category = excluded.category,
  active = excluded.active,
  priority = excluded.priority,
  parser_key = excluded.parser_key,
  last_success_at = excluded.last_success_at,
  last_error_at = excluded.last_error_at,
  consecutive_failures = excluded.consecutive_failures,
  offers_found = excluded.offers_found,
  notes = excluded.notes,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

insert into public.keywords (
  id,
  term,
  type,
  weight,
  active,
  notes,
  created_at,
  updated_at
)
values
  ('kw-design-systems', 'Design Systems', 'include', 1.5, true, 'Señal fuerte de madurez de producto.', timezone('utc', now()), timezone('utc', now())),
  ('kw-design-tokens', 'Design Tokens', 'include', 1.4, true, 'Sistema de interfaces escalable.', timezone('utc', now()), timezone('utc', now())),
  ('kw-figma-variables', 'Figma Variables', 'include', 1.4, true, 'Trabajo actual con variables de diseño.', timezone('utc', now()), timezone('utc', now())),
  ('kw-storybook', 'Storybook', 'include', 1.2, true, 'Documentación viva y colaboración con ingeniería.', timezone('utc', now()), timezone('utc', now())),
  ('kw-wcag', 'WCAG 2.2', 'include', 1.3, true, 'Accesibilidad explícita.', timezone('utc', now()), timezone('utc', now())),
  ('kw-css-html', 'CSS / HTML', 'include', 1.2, true, 'Puente diseño-código y handoff técnico.', timezone('utc', now()), timezone('utc', now())),
  ('kw-design-to-code', 'design-to-code / developer handoff', 'include', 1.2, true, 'Colaboración práctica con frontend.', timezone('utc', now()), timezone('utc', now())),
  ('kw-engineering-collab', 'engineering collaboration', 'include', 1.1, true, 'Trabajo conjunto real.', timezone('utc', now()), timezone('utc', now())),
  ('kw-product-team', 'product team / frontend team', 'include', 1, true, 'Contexto de producto útil.', timezone('utc', now()), timezone('utc', now())),
  ('kw-freelance-contractor', 'freelance / contractor / project-based / temporary', 'exclude', -1.4, true, 'Inestabilidad y menor encaje.', timezone('utc', now()), timezone('utc', now())),
  ('kw-disenador-360', 'diseñador 360 / rockstar / ninja', 'exclude', -1.2, true, 'Rol difuso y poco profesional.', timezone('utc', now()), timezone('utc', now())),
  ('kw-pressure-social', 'trabajo bajo presión / social media / marketing designer', 'exclude', -1.1, true, 'Cultura poco sana o desvío del foco.', timezone('utc', now()), timezone('utc', now())),
  ('kw-frontend-obligatorio', 'frontend avanzado obligatorio', 'exclude', -1, true, 'Deriva hacia desarrollo puro.', timezone('utc', now()), timezone('utc', now())),
  ('kw-jornada-ambigua', 'jornada ambigua / horario poco claro', 'exclude', -0.8, true, 'Clareza laboral insuficiente.', timezone('utc', now()), timezone('utc', now()))
on conflict (id) do update set
  term = excluded.term,
  type = excluded.type,
  weight = excluded.weight,
  active = excluded.active,
  notes = excluded.notes,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

commit;
